name: CI

on: [push]

jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test installation script
        run: |
          chmod +x install.sh
          ./install.sh

